In [36]:
import numpy as np

In [37]:
#numpy arrays
dt = np.float32
x = np.array([1,2,4],dtype=dt)
x.itemsize

4

In [38]:
np.sin(np.array([1,2,3],dtype=np.float32))

array([ 0.84147096,  0.90929741,  0.14112   ], dtype=float32)

In [39]:
from math import sin
[sin(i) for i in [1,2,3]]

[0.8414709848078965, 0.9092974268256817, 0.1411200080598672]

In [40]:
np.sin([1,1,1])

array([ 0.84147098,  0.84147098,  0.84147098])

In [42]:
x = np.array([[1,2,3],[4,5,6]])

In [43]:
x[:,0] #0th column

array([1, 4])

In [44]:
x[:,1]

array([2, 5])

In [48]:
x[:]
x

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
x[:,0:2]

array([[1, 2],
       [4, 5]])

In [54]:
#reverse
x[:,::-1]

array([[3, 2, 1],
       [6, 5, 4]])

In [58]:
x[::-1,]

array([[4, 5, 6],
       [1, 2, 3]])

In [63]:
x[1,:]

array([4, 5, 6])

In [65]:
x = np.ones((3,3))

In [66]:
x

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [68]:
x[:,[0,1,2,2]]

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [81]:
#index by integer creates copy
x = np.arange(5)
y = x[[0,1,2]]
z = x[:3]

In [82]:
print(y) #copy
print(z) #view/slice

[0 1 2]
[0 1 2]


In [83]:
x[0] = 99

In [84]:
print(y)
print(z)

[0 1 2]
[99  1  2]


In [85]:
x[::2] = 99 #every other value

In [86]:
x

array([99,  1, 99,  3, 99])

In [163]:
from numpy.lib.stride_tricks import as_strided
x = np.arange(16)
y = as_strided(x,(7,4),(x.itemsize*2,8))

In [164]:
y

array([[ 0,  1,  2,  3],
       [ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11],
       [10, 11, 12, 13],
       [12, 13, 14, 15]])

In [165]:
n = 8
x = np.arange(n)
k = 5
y = as_strided(x,(k,n-k+1),(x.itemsize,)*2)

In [166]:
y

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [203]:
A = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
x = np.matrix([[1],[0],[0]])
A*x 

matrix([[1],
        [4],
        [7]])

In [204]:
np.dot(A,x)

matrix([[1],
        [4],
        [7]])

In [205]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [212]:
y = np.array([[1],[0],[0]])

In [213]:
x*y

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [214]:
np.dot(x,y)

array([[1],
       [4],
       [7]])

In [218]:
A = np.ones((3,3))
print(type(A))
x = np.ones((3,1))
A*x

<class 'numpy.ndarray'>


array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [220]:
np.matrix(A)*x

matrix([[ 3.],
        [ 3.],
        [ 3.]])

In [221]:
#Numpy Broadcasting

In [26]:
X,y = np.meshgrid(np.matrix([[1,2,3],[4,5,6],[7,8,9]]),np.matrix([[1,2,3],[4,5,6],[7,8,9]]))
print("X is: \n", X) #duplicate by row
print("Y is: \n", y) #duplicate by column

X is: 
 [[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]
Y is: 
 [[1 1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3 3]
 [4 4 4 4 4 4 4 4 4]
 [5 5 5 5 5 5 5 5 5]
 [6 6 6 6 6 6 6 6 6]
 [7 7 7 7 7 7 7 7 7]
 [8 8 8 8 8 8 8 8 8]
 [9 9 9 9 9 9 9 9 9]]


In [18]:
x = np.array([0,1])
y = np.array([0,1])

In [20]:
x + y[:,np.newaxis]

array([[0, 1],
       [1, 2]])

In [33]:
x = np.array([0,1])
y = np.array([0,1,2])
X,Y = np.meshgrid(x,y)
print("With meshgrid: \n",X+Y)
#with broadcasting using newaxis
print("With broadcasting: \n", x+y[:,None])

With meshgrid: 
 [[0 1]
 [1 2]
 [2 3]]
With broadcasting: 
 [[0 1]
 [1 2]
 [2 3]]


In [34]:
#broadcasting works in multiple dimensions
x = np.array([0,1])
y = np.array([0,1,2])
z = np.array([0,1,2,3])
x+y[:,np.newaxis]+z[:,np.newaxis,np.newaxis]

array([[[0, 1],
        [1, 2],
        [2, 3]],

       [[1, 2],
        [2, 3],
        [3, 4]],

       [[2, 3],
        [3, 4],
        [4, 5]],

       [[3, 4],
        [4, 5],
        [5, 6]]])

In [ ]:
#numpy masked arrays

In [37]:
from numpy import ma

In [42]:
#masking doesn't create copy 
x = np.arange(10)
y = np.ma.masked_array(x,x<5) #view
print(x)
print(y)
print(x.shape)
print(y.shape)
x[-1] = 99
print(x)
print(y) #changes as it is a view

[0 1 2 3 4 5 6 7 8 9]
[-- -- -- -- -- 5 6 7 8 9]
(10,)
(10,)
[ 0  1  2  3  4  5  6  7  8 99]
[-- -- -- -- -- 5 6 7 8 99]
