In [53]:
import numpy as np

In [54]:
p = np.array([5,5,5,5.0])

In [55]:
p.ndim

1

In [56]:
p.shape

(4,)

In [57]:
len(p)

4

In [58]:
p.dtype

dtype('float64')

In [59]:
type(p)

numpy.ndarray

In [60]:
intar = p.astype(np.int32)

In [61]:
print(intar)

[5 5 5 5]


In [62]:
arr = np.empty([3,2])

In [63]:
print(arr)

[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]


In [64]:
arr = np.empty([3,2], dtype= np.int64)

In [65]:
print(arr)

[[0 0]
 [0 0]
 [0 0]]


In [66]:
a = np.array([[1,2],[4,3]])

In [67]:
print(a)

[[1 2]
 [4 3]]


In [68]:
np.empty_like(a)

array([[0, 0],
       [0, 0]])

In [69]:
np.eye(2,dtype=np.float64)

array([[ 1.,  0.],
       [ 0.,  1.]])

In [70]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [71]:
np.ones(4,dtype=np.int)

array([1, 1, 1, 1])

In [72]:
np.ones_like(a)

array([[1, 1],
       [1, 1]])

In [73]:
np.zeros(4)

array([ 0.,  0.,  0.,  0.])

In [74]:
np.zeros_like(a)

array([[0, 0],
       [0, 0]])

In [75]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
np.arange(3,10,2)

array([3, 5, 7, 9])

In [77]:
np.full((2,2),3,dtype=np.float)

array([[ 3.,  3.],
       [ 3.,  3.]])

In [78]:
np.full_like(a,5)

array([[5, 5],
       [5, 5]])

In [79]:
np.copy(a)

array([[1, 2],
       [4, 3]])

In [80]:
np.fromstring('3.14 2.15',dtype=np.float, sep=' ')

array([ 3.14,  2.15])

# Indexing and slicing

In [83]:
a = np.arange(7)

In [84]:
a

array([0, 1, 2, 3, 4, 5, 6])

In [85]:
a[1],a[2]

(1, 2)

In [104]:
a = np.array([[1,2,4],[4,5,6],[7,8,11]])

In [106]:
b = a[2]

In [107]:
b

array([ 7,  8, 11])

In [110]:
b[-1] = 99

In [111]:
a

array([[ 1,  2,  4],
       [ 4,  5,  6],
       [ 7,  8, 99]])

In [112]:
b = ((a % 5) ==0)

In [113]:
b

array([[False, False, False],
       [False,  True, False],
       [False, False, False]], dtype=bool)

In [114]:
a

array([[ 1,  2,  4],
       [ 4,  5,  6],
       [ 7,  8, 99]])

In [115]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [125]:
a[[2,1],[2,2]]

array([11,  7])

In [127]:
a = np.ones(4)


In [128]:
a*2

array([ 2.,  2.,  2.,  2.])

In [131]:
a+1

array([ 2.,  2.,  2.,  2.])

In [132]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])

In [133]:
a == b

array([ True,  True,  True,  True], dtype=bool)

In [134]:
np.array_equal(a,b)

True

In [136]:
np.logical_and(a,b)

array([ True,  True,  True,  True], dtype=bool)